"use client";

import { useState } from "react";
import * as S from "@/lib/storage";
import { fmtCurrency, fmtDateDisp, parseMoney } from "@/lib/utils";

function Icon({ d, size = 15 }: { d: string; size?: number }) {
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d={d} /></svg>;
}
const I = {
  wallet: "M21 12V7H5a2 2 0 0 1 0-4h14v4M3 5v14a2 2 0 0 0 2 2h16v-5M18 12a2 2 0 0 0 0 4h4v-4Z",
  dream: "M12 3l2.4 4.86L20 8.67l-4 3.9.94 5.5L12 15.5l-4.94 2.57.94-5.5-4-3.9 5.6-.81z",
  think: "M9 18h6M10 22h4M8.5 14.5A6 6 0 1 1 15.5 14.5c-.9.7-1.5 1.5-1.5 2.5h-4c0-1-.6-1.8-1.5-2.5z",
  calc: "M4 2h16v20H4zM8 6h8v4H8zM8 14h.01M12 14h.01M16 14h.01M8 18h.01M12 18h.01M16 18h.01",
  plus: "M12 5v14M5 12h14", x: "M18 6 6 18M6 6l12 12", check: "M20 6 9 17l-5-5",
};
const input = "w-full px-3 py-2.5 rounded-lg bg-bg2 border border-line text-sm outline-none focus:border-ink min-h-[44px]";

function MoneyField({ value, onChange, placeholder }: { value: string; onChange: (v: string) => void; placeholder: string }) {
  const n = parseMoney(value);
  return <div><input value={value} onChange={e => onChange(e.target.value)} inputMode="decimal" placeholder={placeholder} className={input} />{value && <div className={`text-[9px] text-right mt-0.5 ${n == null ? "text-red" : "text-green"}`}>{n == null ? "Sai số tiền" : fmtCurrency(n)}</div>}</div>;
}

type Tool = "money" | "dream" | "think" | "calc";
export default function FinanceTools() {
  const [open, setOpen] = useState<Tool | null>(null);
  const [, refresh] = useState(0);
  const reload = () => refresh(x => x + 1);
  const tools = [
    { k: "money" as const, l: "Tiền", sub: fmtCurrency(S.getTotalMoney()), d: I.wallet },
    { k: "dream" as const, l: "Mơ ước", sub: `${S.getDreamItems().length} mục`, d: I.dream },
    { k: "think" as const, l: "Có nên mua?", sub: "phân tích", d: I.think },
    { k: "calc" as const, l: "Máy tính", sub: "tính nhanh", d: I.calc },
  ];
  return <section className="bg-card rounded-xl border border-line overflow-hidden">
    <div className="grid grid-cols-4 gap-1 p-1">
      {tools.map(t => <button key={t.k} onClick={() => setOpen(open === t.k ? null : t.k)} className={`min-h-[54px] rounded-lg flex flex-col items-center justify-center gap-0.5 text-[9px] font-bold ${open === t.k ? "bg-ink text-bg" : "bg-bg2 text-mute hover:text-ink"}`}><Icon d={t.d} size={15}/><span>{t.l}</span><span className={`text-[7px] font-normal truncate max-w-full px-1 ${open === t.k ? "text-bg/60" : "text-mute2"}`}>{t.sub}</span></button>)}
    </div>
    {open && <div className="border-t border-line max-h-[380px] overflow-y-auto overscroll-contain">
      <div className="sticky top-0 bg-card z-10 px-3 py-1.5 border-b border-line flex justify-between items-center"><span className="text-[10px] font-bold">{tools.find(t=>t.k===open)?.l}</span><button onClick={()=>setOpen(null)} className="w-8 h-8 flex items-center justify-center text-mute"><Icon d={I.x} size={12}/></button></div>
      {open === "money" && <MoneyPanel onChanged={reload}/>} {open === "dream" && <DreamPanel onChanged={reload}/>} {open === "think" && <DecisionPanel onChanged={reload}/>} {open === "calc" && <Calculator/>}
    </div>}
  </section>;
}

function MoneyPanel({onChanged}:{onChanged:()=>void}) {
  const accounts=S.getMoneyAccounts(), total=S.getTotalMoney(); const [add,setAdd]=useState(false); const [name,setName]=useState(""); const [type,setType]=useState<S.MoneyAccount["type"]>("bank"); const [bal,setBal]=useState("");
  return <div className="p-3 space-y-2"><div className="flex justify-between items-end"><div><div className="text-[9px] text-mute font-bold">TỔNG TIỀN HIỆN CÓ</div><div className="text-xl font-bold text-green tnum">{fmtCurrency(total)}</div></div><button onClick={()=>setAdd(!add)} className="w-9 h-9 rounded-lg bg-ink text-bg flex items-center justify-center"><Icon d={add?I.x:I.plus}/></button></div>
  {add&&<div className="space-y-1.5 bg-bg2 border border-line rounded-lg p-2"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Tên ngân hàng / tiền mặt" className={input}/><div className="grid grid-cols-4 gap-1">{(["cash","bank","ewallet","other"] as const).map(t=><button key={t} onClick={()=>setType(t)} className={`min-h-[38px] rounded-md text-[8px] font-bold ${type===t?"bg-ink text-bg":"bg-card border border-line text-mute"}`}>{t==="cash"?"Tiền mặt":t==="bank"?"Ngân hàng":t==="ewallet"?"Ví điện tử":"Khác"}</button>)}</div><MoneyField value={bal} onChange={setBal} placeholder="Số dư"/><button onClick={()=>{const n=parseMoney(bal);if(!name.trim()||n==null)return;S.addMoneyAccount({name:name.trim(),type,balance:n,color:"#4db8ff"});setAdd(false);setName("");setBal("");onChanged();}} className="w-full min-h-[44px] bg-ink text-bg rounded-lg text-[10px] font-bold">Lưu</button></div>}
  {accounts.map(a=><div key={a.id} className="flex items-center gap-2 bg-bg2 border border-line rounded-lg px-2 py-2"><div className="flex-1"><div className="text-[10px] font-bold">{a.name}</div><div className="text-[8px] text-mute">{a.type}</div></div><span className="text-[11px] font-bold tnum">{fmtCurrency(a.balance)}</span><button onClick={()=>{const v=prompt("Cộng/trừ tiền (500k hoặc -200k):");if(!v)return;const neg=v.startsWith("-");const n=parseMoney(v.replace("-",""));if(n!=null){S.adjustMoneyAccount(a.id,neg?-n:n);onChanged();}}} className="w-8 h-8 bg-card border border-line rounded-md">±</button><button onClick={()=>{if(confirm("Xóa?")){S.deleteMoneyAccount(a.id);onChanged();}}} className="w-8 h-8 flex items-center justify-center text-mute"><Icon d={I.x} size={11}/></button></div>)}</div>;
}

function DreamPanel({onChanged}:{onChanged:()=>void}) {
  const items=S.getDreamItems(), money=S.getTotalMoney(), debt=S.getTotalDebt(); const [step,setStep]=useState<0|1|2>(0); const [name,setName]=useState("");const [price,setPrice]=useState("");const [saved,setSaved]=useState("");const [monthly,setMonthly]=useState("");const [reserve,setReserve]=useState("");const [reason,setReason]=useState("");
  const pr=parseMoney(price)||0, sv=parseMoney(saved)||0, mo=parseMoney(monthly)||0, rs=parseMoney(reserve)||0; const remain=Math.max(0,pr-sv), months=mo>0?Math.ceil(remain/mo):null; let verdict="Cần nhập giá món đồ"; let vc="text-mute"; if(pr>0){if(sv>=pr){verdict="Đã đủ quỹ — có thể mua";vc="text-green";}else if(debt>0){verdict="Ưu tiên trả nợ trước, tiếp tục để dành";vc="text-red";}else if(money>=pr+rs){verdict="Đủ khả năng, nhưng nên chờ 48h trước khi mua";vc="text-gold";}else{verdict=months?`Cần khoảng ${months} tháng để đủ quỹ`:"Chưa nên mua — hãy đặt mức để dành mỗi tháng";vc="text-gold";}}
  return <div className="p-3 space-y-2">
    {step===0&&<><div className="text-[10px] text-mute">Mỗi mục trả lời 3 câu: giá bao nhiêu, đang có bao nhiêu, dành được bao nhiêu mỗi tháng.</div><button onClick={()=>setStep(1)} className="w-full min-h-[44px] bg-ink text-bg rounded-lg text-[10px] font-bold">+ Thêm món muốn mua</button>{items.map(d=>{const rem=Math.max(0,d.price-d.savedAmount),pct=Math.min(100,Math.round(d.savedAmount/d.price*100)),ms=d.monthlySaving>0?Math.ceil(rem/d.monthlySaving):null;return <div key={d.id} className="bg-bg2 border border-line rounded-lg p-2"><div className="flex justify-between"><div className="text-[11px] font-bold">{d.name}</div><div className="text-[11px] font-bold tnum">{fmtCurrency(d.price)}</div></div><div className="h-1.5 bg-card rounded-full my-1"><div className="h-full bg-green rounded-full" style={{width:`${pct}%`}}/></div><div className="text-[9px] text-mute">Đã dành {fmtCurrency(d.savedAmount)} · Còn {fmtCurrency(rem)}{ms?` · ≈ ${ms} tháng`:""}</div><div className="flex gap-1 mt-1.5"><button onClick={()=>{const v=prompt("Thêm vào quỹ:");const n=v?parseMoney(v):null;if(n){S.contributeDream(d.id,n);onChanged();}}} className="flex-1 min-h-[34px] bg-green2 text-green border border-green/20 rounded-md text-[9px] font-bold">+ Để dành</button><button onClick={()=>{if(confirm("Xóa?")){S.deleteDreamItem(d.id);onChanged();}}} className="w-8 h-8 text-mute"><Icon d={I.x} size={10}/></button></div></div>;})}</>}
    {step===1&&<><div className="text-[10px] font-bold">Bước 1/2 · Món đồ và số tiền</div><input value={name} onChange={e=>setName(e.target.value)} placeholder="Tên món muốn mua" className={input} autoFocus/><MoneyField value={price} onChange={setPrice} placeholder="Giá món đồ"/><MoneyField value={saved} onChange={setSaved} placeholder="Đã để dành được"/><button onClick={()=>setStep(2)} disabled={!name.trim()||pr<=0} className="w-full min-h-[44px] bg-ink text-bg rounded-lg text-[10px] font-bold disabled:opacity-30">Tiếp theo →</button></>}
    {step===2&&<><div className="text-[10px] font-bold">Bước 2/2 · Kế hoạch để dành</div><MoneyField value={monthly} onChange={setMonthly} placeholder="Có thể để dành mỗi tháng"/><MoneyField value={reserve} onChange={setReserve} placeholder="Quỹ dự phòng không được đụng"/><input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Vì sao muốn mua?" className={input}/><div className="bg-bg2 border border-line rounded-lg p-2"><div className={`text-[11px] font-bold ${vc}`}>{verdict}</div>{months&&<div className="text-[9px] text-mute mt-0.5">Còn {fmtCurrency(remain)} · khoảng {months} tháng</div>}</div><div className="flex gap-1.5"><button onClick={()=>setStep(1)} className="px-4 min-h-[44px] bg-bg2 border border-line rounded-lg">←</button><button onClick={()=>{S.addDreamItem({name:name.trim(),category:"want",price:pr,savedAmount:sv,monthlySaving:mo,reserveAmount:rs,priority:1,targetDate:null,reason:reason||null,status:"saving"});setStep(0);onChanged();}} className="flex-1 min-h-[44px] bg-ink text-bg rounded-lg text-[10px] font-bold">Lưu mục tiêu</button></div></>}
  </div>;
}

function DecisionPanel({onChanged}:{onChanged:()=>void}) {
  const [step,setStep]=useState<0|1|2>(0); const [name,setName]=useState("");const [price,setPrice]=useState("");const [monthly,setMonthly]=useState("");const [uses,setUses]=useState("");const [importance,setImportance]=useState(3);const [urgency,setUrgency]=useState(2);const [alt,setAlt]=useState(false);const [reason,setReason]=useState("");const [type,setType]=useState<S.BuyDecision["type"]>("item");
  const money=S.getTotalMoney(),debt=S.getTotalDebt(),p=parseMoney(price)||0,mp=parseMoney(monthly)||0,annual=type==="subscription"?mp*12:p,use=Math.max(1,+uses||1),perUse=annual/use,burden=money>0?annual/money:99;let score=Math.round(importance*14+urgency*8-(alt?12:0)-Math.min(40,burden*40)-(debt>0?12:0));score=Math.max(0,Math.min(100,score));const result=score>=68&&annual<=money?"CÓ THỂ MUA — tài chính cho phép":score>=42?"NÊN CHỜ 7 NGÀY — xem nhu cầu còn giữ nguyên không":"CHƯA NÊN MUA — áp lực tài chính hoặc ít cần thiết";const rc=score>=68?"text-green":score>=42?"text-gold":"text-red";
  return <div className="p-3 space-y-2">
    {step===0&&<><div className="bg-bg2 border border-line rounded-lg p-2"><div className="text-[11px] font-bold">Công cụ này trả lời: mua ngay, chờ hay không mua?</div><div className="text-[9px] text-mute mt-0.5">Bạn chỉ cần nhập giá và trả lời mức cần thiết. Web so với tiền và nợ hiện có.</div></div><button onClick={()=>setStep(1)} className="w-full min-h-[44px] bg-ink text-bg rounded-lg text-[10px] font-bold">Bắt đầu cân nhắc</button>{S.getBuyDecisions().slice(0,3).map(d=><div key={d.id} className="flex gap-2 items-center bg-bg2 border border-line rounded-lg p-2"><div className="flex-1"><div className="text-[10px] font-bold">{d.name}</div><div className="text-[9px] text-mute">{d.result}</div></div><span className={`text-[11px] font-bold ${d.score>=68?"text-green":d.score>=42?"text-gold":"text-red"}`}>{d.score}</span><button onClick={()=>{S.deleteBuyDecision(d.id);onChanged();}} className="text-mute"><Icon d={I.x} size={10}/></button></div>)}</>}
    {step===1&&<><div className="text-[10px] font-bold">Bước 1/2 · Bạn định mua gì?</div><input value={name} onChange={e=>setName(e.target.value)} placeholder="Tên món / gói cước / khóa học" className={input} autoFocus/><div className="grid grid-cols-4 gap-1">{(["item","subscription","course","service"] as const).map(t=><button key={t} onClick={()=>setType(t)} className={`min-h-[38px] rounded-md text-[8px] font-bold ${type===t?"bg-ink text-bg":"bg-bg2 border border-line text-mute"}`}>{t==="item"?"Món đồ":t==="subscription"?"Gói cước":t==="course"?"Khóa học":"Dịch vụ"}</button>)}</div>{type==="subscription"?<MoneyField value={monthly} onChange={setMonthly} placeholder="Phí mỗi tháng"/>:<MoneyField value={price} onChange={setPrice} placeholder="Giá phải trả"/>}<input type="number" value={uses} onChange={e=>setUses(e.target.value)} placeholder="Số lần sẽ dùng trong 1 năm" className={input}/><button onClick={()=>setStep(2)} disabled={!name.trim()||annual<=0} className="w-full min-h-[44px] bg-ink text-bg rounded-lg text-[10px] font-bold disabled:opacity-30">Tiếp theo →</button></>}
    {step===2&&<><div className="text-[10px] font-bold">Bước 2/2 · Trả lời thật</div><label className="block text-[9px] text-mute">Cần thiết đến mức nào? <b>{importance}/5</b><input type="range" min="1" max="5" value={importance} onChange={e=>setImportance(+e.target.value)} className="w-full"/></label><label className="block text-[9px] text-mute">Cần mua sớm đến mức nào? <b>{urgency}/5</b><input type="range" min="1" max="5" value={urgency} onChange={e=>setUrgency(+e.target.value)} className="w-full"/></label><label className="flex gap-2 items-center text-[10px] text-mute"><input type="checkbox" checked={alt} onChange={e=>setAlt(e.target.checked)}/>Có lựa chọn rẻ hơn hoặc miễn phí</label><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Lợi ích thật sự nếu mua" rows={2} className={`${input} resize-none`}/><div className="bg-bg2 border border-line rounded-lg p-2.5"><div className={`text-[12px] font-bold ${rc}`}>{result}</div><div className="text-[9px] text-mute mt-1">Điểm: {score}/100 · Chi phí/năm: {fmtCurrency(annual)} · Mỗi lần dùng: {fmtCurrency(Math.round(perUse))}</div><div className="text-[9px] text-mute">Tiền hiện có: {fmtCurrency(money)} · Tổng nợ: {fmtCurrency(debt)}</div></div><div className="flex gap-1.5"><button onClick={()=>setStep(1)} className="px-4 min-h-[44px] bg-bg2 border border-line rounded-lg">←</button><button onClick={()=>{S.addBuyDecision({name:name.trim(),type,price:p,monthlyPrice:mp,expectedUses:use,importance,urgency,hasAlternative:alt,notes:reason||null,result,score});setStep(0);onChanged();}} className="flex-1 min-h-[44px] bg-ink text-bg rounded-lg text-[10px] font-bold">Lưu kết quả</button></div></>}
  </div>;
}

function Calculator(){const[expr,setExpr]=useState("");const[result,setResult]=useState("0");const calc=()=>{try{if(!/^[0-9+\-*/().%\s]+$/.test(expr))throw 0;const v=Function(`"use strict";return (${expr.replace(/%/g,"/100")})`)();if(!Number.isFinite(v))throw 0;setResult(new Intl.NumberFormat("vi-VN",{maximumFractionDigits:4}).format(v));}catch{setResult("Lỗi");}};return <div className="p-3"><div className="bg-bg2 border border-line rounded-lg p-3 text-right mb-2"><input value={expr} onChange={e=>setExpr(e.target.value)} inputMode="decimal" placeholder="0" className="w-full bg-transparent text-right text-sm outline-none"/><div className="text-2xl font-bold tnum mt-1">{result}</div></div><div className="grid grid-cols-4 gap-1.5">{["7","8","9","/","4","5","6","*","1","2","3","-","0",".","%","+","(",")","C","="].map(k=><button key={k} onClick={()=>{if(k==="C"){setExpr("");setResult("0");}else if(k==="=")calc();else setExpr(expr+k);}} className={`min-h-[44px] rounded-lg font-bold text-sm ${k==="="?"bg-ink text-bg":/[+\-*/]/.test(k)?"bg-gold2 text-gold border border-gold/20":"bg-bg2 border border-line"}`}>{k}</button>)}</div></div>}
